#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: quickchat-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#    - host: quickchat.com
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: quickchat
#                port:
#                  number: 8080
