apiVersion: v1
kind: Service
metadata:
  name: quickchat
spec:
  type: NodePort
  selector:
    app: quickchat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30036  # You can choose any port between 30000–32767
