server:
  port: 8080

spring:
  application:
    name: quickchat
  data:
    mongodb:
      uri: mongodb://localhost:27017/quickchat
      //uri: mongodb://host.docker.internal:27017/quickchat
  security:
    user:
      name: admin
      password: admin
